import numpy as np
import matplotlib.pyplot as plt

MEASURES = (
    'gentime',
    'edge',
    'poweredge',
    'powernode',
)
LABELS = (
    'time per step',
    'remaining edges',
    'generated poweredge',
    'generated powernode',
)
COLORS = (
    'black',
    'green',
    'blue',
    'red'
)


def plots(filename, title="statistics", xlabel='step', ylabel='measures'):
    """Generate the plot that show all the data generated by the compression"""

    # GET DATA
    data = np.genfromtxt(
        filename,
        delimiter=',',
        skip_header=0,
        skip_footer=0,
        names=True,  # read names from header
    )

    # PLOTTING
    fig = plt.figure()
    ax1 = fig.add_subplot(111)
    xaxis = np.linspace(0,1,len(data[MEASURES[0]]))

    ax1.set_title(title)
    ax1.set_xlabel(xlabel)
    ax1.set_ylabel(ylabel)

    for measure, label, color in zip(MEASURES, LABELS, COLORS):
        ax1.plot(
            xaxis,
            data[measure],
            color=color,
            label=label,
        )

    leg = ax1.legend()

    plt.show()
