"""
Test on unambiguous graph compression that prioritize nodes with
the greater degree.

"""
import unittest
import tempfile

from powergrasp import commons
from powergrasp import recipes
from powergrasp import solving
from powergrasp import config


class TestNaiveTheoremUnambiguousCompression(unittest.TestCase):
    """This class yields many subtests about theorem method
    and unambiguous compression results.

    The test case and associated results are defined in setUp() method.
    Bubble outputs are comparated, excluding comments and empty lines.

    The unambiguous compression is important : bubble comparison is sensitive
    to powernodes numbers and related.
    However, it resists to multiple connected components.

    """

    def setUp(self):
        self.test_cases = {
            'prio_deg.lp'             : RESULT_PRIODEG,
            'empty.lp'                : '',
        }


    def unified_bubble(self, bubble_lines):
        """Return the set of comparable lines found in given bubble lines"""
        # filter out comments and blank lines
        return set(line.strip() for line in bubble_lines
                   if not line.startswith('#') and len(line.strip()) > 0)

    def unified_bubble_from_file(self, bubble_file):
        """Return the set of comparable lines found in given bubble file"""
        with open(bubble_file) as fd:
            return self.unified_bubble(fd)

    def assert_equality(self, input_filename, expected_bubble):
        """call assertEqual to compare given bubble and bubble generated by
        compressing given graph."""
        # create the temp file to be write by the compression
        tmp = tempfile.NamedTemporaryFile('w', delete=False)
        tmp.close()
        # launch the compression itself, then compare result with expected
        with self.subTest(filename=input_filename):
            print('TEST CASE:', input_filename)
            cfg = config.Configuration.fields_for_naive_dichotomic_search(
                infile=input_filename,
                outfile=tmp.name,
                outformat='bbl',
                loglevel='CRITICAL',
            )
            recipes.powergraph(cfg=cfg)
            expected = self.unified_bubble(expected_bubble)
            found = self.unified_bubble_from_file(tmp.name)
            self.assertEqual(expected, found)


    def test_cases(self):
        for filename, expected in self.test_cases.items():
            self.assert_equality(
                commons.test_case(filename),
                expected.split('\n'),
            )


RESULT_PRIODEG = """
NODE\tc
NODE\te
NODE\tf
NODE\td
NODE\th
NODE\tg
NODE\tb
NODE\ta
IN\tg\tPWRN-a-2-1
IN\tf\tPWRN-a-2-1
IN\th\tPWRN-a-2-1
IN\tc\tPWRN-a-1-1
IN\tb\tPWRN-a-1-1
IN\ta\tPWRN-a-1-1
IN\te\tPWRN-a-1-2
IN\td\tPWRN-a-1-2
EDGE\tPWRN-a-2-1\ts\t1.0
EDGE\tPWRN-a-1-1\tPWRN-a-1-2\t1.0
EDGE\ta\ts\t1.0
"""
